-- Password reset template for user accounts
-- IMPORTANT: Do NOT hardcode passwords in SQL files.
-- Use the application's password reset endpoint or the reset_password.mjs script
-- with environment variables instead.
--
-- Example usage:
--   NEW_PASSWORD=<your-password> DATABASE_URL=<url> node reset_password.mjs
