-- Password update template
-- IMPORTANT: Do NOT hardcode passwords or bcrypt hashes in SQL files.
-- Use the application's password reset endpoint or the reset_password.mjs script
-- with environment variables instead.
--
-- Example usage:
--   NEW_PASSWORD=<your-password> DATABASE_URL=<url> node reset_password.mjs
--
-- To generate a bcrypt hash programmatically:
--   node -e "const bcrypt = require('bcryptjs'); bcrypt.hash(process.env.PASSWORD, 10).then(h => console.log(h))"
