-- User role/status update template
-- IMPORTANT: Do NOT hardcode passwords or bcrypt hashes in SQL files.
--
-- To update a user's role:
--   UPDATE users SET role = 'admin' WHERE email = '<email>';
--
-- To reset a password, use the reset_password.mjs script:
--   NEW_PASSWORD=<password> DATABASE_URL=<url> node reset_password.mjs
