CREATE TABLE `advancedOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productName` varchar(200) NOT NULL,
	`productPrice` decimal(10,2) NOT NULL,
	`customerName` varchar(100) NOT NULL,
	`customerPhone` varchar(20) NOT NULL,
	`governorate` varchar(100) NOT NULL,
	`detailedLocation` text NOT NULL,
	`delegateName` varchar(100) NOT NULL,
	`delegateCommission` decimal(10,2),
	`orderDate` timestamp NOT NULL DEFAULT (now()),
	`orderNotes` text,
	`weight` varchar(50),
	`length` varchar(50),
	`color` varchar(50),
	`size` varchar(50),
	`warehouseCode` varchar(50) NOT NULL,
	`images` text,
	`videos` text,
	`status` enum('pending','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending',
	`whatsappSent` boolean NOT NULL DEFAULT false,
	`emailSent` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `advancedOrders_id` PRIMARY KEY(`id`)
);
